<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VietRide.Trip.Domain\VietRide.Trip.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\libs\dotnet\VietRide.Shared.Kernel\VietRide.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\..\libs\dotnet\VietRide.Shared.Application\VietRide.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\libs\dotnet\VietRide.Shared.Messaging\VietRide.Shared.Messaging.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
