// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Parcel.Infrastructure;

#nullable disable

namespace VietRide.Parcel.Infrastructure.Migrations
{
    [DbContext(typeof(ParcelDbContext))]
    partial class ParcelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_parcel")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_parcel", "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_parcel", "parcel_delivery_method", new[] { "TERMINAL_PICKUP" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_parcel", "parcel_review_decision", new[] { "PENDING", "APPROVED", "REJECTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_parcel", "parcel_size_category", new[] { "SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_parcel", "parcel_status", new[] { "PENDING_OPERATOR_REVIEW", "PENDING_PAYMENT", "PENDING", "PENDING_ADDITIONAL_PAYMENT", "LOADED", "IN_TRANSIT", "PENDING_TRANSFER_CONFIRM", "TRANSFER_ESCALATED", "UNLOADED", "DELIVERED_PENDING_CONFIRM", "DELIVERY_CONFIRMED", "DELIVERY_REJECTED", "RETURN_INITIATED", "RETURNED", "PENDING_OPERATOR_ACTION", "CANCELLED", "REJECTED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Parcel.Domain.Entities.OperatorDepositPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DepositPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("deposit_percent");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_operator_deposit_policies");

                    b.HasIndex("OperatorId", "RouteId", "IsActive", "EffectiveFrom")
                        .HasDatabaseName("idx_operator_deposit_policies_lookup");

                    b.ToTable("operator_deposit_policies", "vietride_parcel", t =>
                        {
                            t.HasCheckConstraint("chk_operator_deposit_policies_percent", "deposit_percent > 0 AND deposit_percent <= 100");
                        });
                });

            modelBuilder.Entity("VietRide.Parcel.Domain.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("ActualChargeableWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_chargeable_weight_kg");

                    b.Property<decimal?>("ActualDimWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_dim_weight_kg");

                    b.Property<decimal?>("ActualHeightCm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_height_cm");

                    b.Property<decimal?>("ActualLengthCm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_length_cm");

                    b.Property<decimal?>("ActualVolumeM3")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("actual_volume_m3");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_weight_kg");

                    b.Property<decimal?>("ActualWidthCm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("actual_width_cm");

                    b.Property<long>("AdditionalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("additional_amount")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset?>("AdditionalPaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("additional_payment_deadline");

                    b.Property<Guid?>("AdditionalPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("additional_payment_id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("ConfirmNote")
                        .HasColumnType("text")
                        .HasColumnName("confirm_note");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("confirmed_by_ip");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeliveredPendingConfirmAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_pending_confirm_at");

                    b.Property<int>("DeliveryMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_parcel.parcel_delivery_method")
                        .HasColumnName("delivery_method")
                        .HasDefaultValueSql("'TERMINAL_PICKUP'");

                    b.Property<Guid?>("DeliveryToken")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_token");

                    b.Property<DateTimeOffset?>("DeliveryTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_token_expires_at");

                    b.Property<DateTimeOffset?>("DeliveryTokenRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_token_revoked_at");

                    b.Property<long>("DepositAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("deposit_amount");

                    b.Property<decimal>("DepositPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(100m)
                        .HasColumnName("deposit_percent");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("DropoffStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropoff_stop_id");

                    b.Property<decimal>("EstimatedChargeableWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0.01m)
                        .HasColumnName("estimated_chargeable_weight_kg");

                    b.Property<decimal>("EstimatedDimWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0.01m)
                        .HasColumnName("estimated_dim_weight_kg");

                    b.Property<decimal>("EstimatedHeightCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("estimated_height_cm");

                    b.Property<decimal>("EstimatedLengthCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("estimated_length_cm");

                    b.Property<decimal>("EstimatedVolumeM3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,4)")
                        .HasDefaultValue(0.0001m)
                        .HasColumnName("estimated_volume_m3");

                    b.Property<decimal>("EstimatedWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("estimated_weight_kg");

                    b.Property<decimal>("EstimatedWidthCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("estimated_width_cm");

                    b.Property<DateTimeOffset?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reminder_at");

                    b.Property<DateTimeOffset?>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<Guid?>("LoadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("loaded_by_user_id");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<long>("OriginalDepositAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("original_deposit_amount");

                    b.Property<string>("ParcelCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("parcel_code");

                    b.Property<string>("PendingActionReason")
                        .HasColumnType("text")
                        .HasColumnName("pending_action_reason");

                    b.Property<string>("PendingActionType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("pending_action_type");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_phone");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<long>("RefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refund_amount")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("text")
                        .HasColumnName("return_reason");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<Guid?>("ReturnedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("returned_by_user_id");

                    b.Property<int?>("ReviewDecision")
                        .HasColumnType("vietride_parcel.parcel_review_decision")
                        .HasColumnName("review_decision");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<int>("SizeCategory")
                        .HasColumnType("vietride_parcel.parcel_size_category")
                        .HasColumnName("size_category");

                    b.Property<int>("Status")
                        .HasColumnType("vietride_parcel.parcel_status")
                        .HasColumnName("status");

                    b.Property<long>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("total_price_vnd")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset?>("TransferConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transfer_confirmed_at");

                    b.Property<Guid?>("TransferConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_confirmed_by_user_id");

                    b.Property<DateTimeOffset?>("TransferRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transfer_requested_at");

                    b.Property<Guid?>("TransferTargetTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_target_trip_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("UnloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unloaded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voucher_code");

                    b.Property<Guid?>("VoucherUsageId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_usage_id");

                    b.HasKey("Id")
                        .HasName("pk_parcels");

                    b.HasIndex("AdditionalPaymentDeadline")
                        .HasDatabaseName("idx_parcels_additional_payment_deadline")
                        .HasFilter("status = 'PENDING_ADDITIONAL_PAYMENT'::vietride_parcel.parcel_status");

                    b.HasIndex("AdditionalPaymentId")
                        .HasDatabaseName("idx_parcels_additional_payment_id")
                        .HasFilter("additional_payment_id IS NOT NULL");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("idx_parcels_confirmed_by_user_id")
                        .HasFilter("confirmed_by_user_id IS NOT NULL");

                    b.HasIndex("DeliveryToken")
                        .IsUnique()
                        .HasDatabaseName("uq_parcels_delivery_token")
                        .HasFilter("delivery_token IS NOT NULL");

                    b.HasIndex("LoadedByUserId")
                        .HasDatabaseName("idx_parcels_loaded_by_user_id")
                        .HasFilter("loaded_by_user_id IS NOT NULL");

                    b.HasIndex("ParcelCode")
                        .IsUnique()
                        .HasDatabaseName("uq_parcels_parcel_code");

                    b.HasIndex("ReturnedByUserId")
                        .HasDatabaseName("idx_parcels_returned_by_user_id")
                        .HasFilter("returned_by_user_id IS NOT NULL");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("idx_parcels_reviewed_by_user_id")
                        .HasFilter("reviewed_by_user_id IS NOT NULL");

                    b.HasIndex("TransferConfirmedByUserId")
                        .HasDatabaseName("idx_parcels_transfer_confirmed_by_user_id")
                        .HasFilter("transfer_confirmed_by_user_id IS NOT NULL");

                    b.HasIndex("TransferTargetTripId")
                        .HasDatabaseName("idx_parcels_transfer_target_trip_id")
                        .HasFilter("transfer_target_trip_id IS NOT NULL");

                    b.HasIndex("VoucherUsageId")
                        .HasDatabaseName("idx_parcels_voucher_usage_id")
                        .HasFilter("voucher_usage_id IS NOT NULL");

                    b.HasIndex("ConfirmedAt", "OperatorId")
                        .HasDatabaseName("idx_parcels_confirmed_report")
                        .HasFilter("status = 'DELIVERY_CONFIRMED'::vietride_parcel.parcel_status AND confirmed_at IS NOT NULL");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_parcels_operator_id_status");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_parcels_recipient_user_id_created_at")
                        .HasFilter("recipient_user_id IS NOT NULL");

                    b.HasIndex("SenderUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_parcels_sender_user_id_created_at");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("idx_parcels_status_updated_at")
                        .HasFilter("status IN ('PENDING'::vietride_parcel.parcel_status, 'PENDING_ADDITIONAL_PAYMENT'::vietride_parcel.parcel_status, 'PENDING_OPERATOR_REVIEW'::vietride_parcel.parcel_status, 'PENDING_OPERATOR_ACTION'::vietride_parcel.parcel_status, 'PENDING_TRANSFER_CONFIRM'::vietride_parcel.parcel_status, 'DELIVERED_PENDING_CONFIRM'::vietride_parcel.parcel_status, 'DELIVERY_REJECTED'::vietride_parcel.parcel_status, 'TRANSFER_ESCALATED'::vietride_parcel.parcel_status)");

                    b.HasIndex("TripId", "Status")
                        .HasDatabaseName("idx_parcels_trip_id_status");

                    b.ToTable("parcels", "vietride_parcel", t =>
                        {
                            t.HasCheckConstraint("chk_parcels_actual_dimensions_positive", "(actual_length_cm IS NULL AND actual_width_cm IS NULL AND actual_height_cm IS NULL) OR (actual_length_cm > 0 AND actual_width_cm > 0 AND actual_height_cm > 0)");

                            t.HasCheckConstraint("chk_parcels_actual_weight_positive", "actual_weight_kg IS NULL OR actual_weight_kg > 0");

                            t.HasCheckConstraint("chk_parcels_amounts_non_negative", "deposit_amount >= 0 AND additional_amount >= 0");

                            t.HasCheckConstraint("chk_parcels_dimensions_positive", "estimated_length_cm > 0 AND estimated_width_cm > 0 AND estimated_height_cm > 0");

                            t.HasCheckConstraint("chk_parcels_volume_positive", "estimated_volume_m3 > 0");

                            t.HasCheckConstraint("chk_parcels_weight_positive", "estimated_weight_kg > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Parcel.Domain.Entities.ParcelRouteFare", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SizeCategory")
                        .HasColumnType("vietride_parcel.parcel_size_category")
                        .HasColumnName("size_category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<long>("MinimumPriceVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("minimum_price_vnd")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<long>("PricePerChargeableKgVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("price_per_chargeable_kg_vnd")
                        .HasDefaultValueSql("0");

                    b.Property<long>("PriceVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("price_vnd");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RouteId", "SizeCategory")
                        .HasName("pk_parcel_route_fares");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_parcel_route_fares_operator_id");

                    b.ToTable("parcel_route_fares", "vietride_parcel", t =>
                        {
                            t.HasCheckConstraint("chk_parcel_route_fares_effective_order", "effective_until IS NULL OR effective_until > effective_from");

                            t.HasCheckConstraint("chk_parcel_route_fares_price_non_negative", "price_vnd >= 0");

                            t.HasCheckConstraint("chk_parcel_route_fares_weight_price_non_negative", "price_per_chargeable_kg_vnd >= 0 AND minimum_price_vnd >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Parcel.Domain.Entities.ParcelStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<int>("TotalDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_delivered");

                    b.Property<int>("TotalLoaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_loaded");

                    b.Property<int>("TotalParcels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_parcels");

                    b.Property<long>("TotalRefunded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_refunded");

                    b.Property<int>("TotalRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_rejected");

                    b.Property<int>("TotalReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_returned");

                    b.Property<long>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_revenue");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_parcel_stats");

                    b.HasIndex("StatDate")
                        .IsDescending()
                        .HasDatabaseName("idx_parcel_stats_stat_date");

                    b.HasIndex("OperatorId", "StatDate")
                        .IsUnique()
                        .HasDatabaseName("uq_parcel_stats_operator_date");

                    b.ToTable("parcel_stats", "vietride_parcel");
                });

            modelBuilder.Entity("VietRide.Parcel.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("decimal_value");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_system_configs");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_system_configs_key_version");

                    b.HasIndex("Key", "IsActive", "EffectiveFrom")
                        .HasDatabaseName("idx_system_configs_lookup");

                    b.ToTable("system_configs", "vietride_parcel", t =>
                        {
                            t.HasCheckConstraint("chk_system_configs_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Inbox.IntegrationInboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_integration_inbox");

                    b.HasIndex("ConsumerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("uq_integration_inbox_consumer_message");

                    b.ToTable("integration_inbox", "vietride_parcel");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxDlq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("TerminalAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_outbox_dlq");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_outbox_dlq_event_id");

                    b.HasIndex("TerminalAt", "EventId")
                        .IsDescending()
                        .HasDatabaseName("idx_outbox_dlq_terminal_event_id");

                    b.ToTable("outbox_dlq", "vietride_parcel");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_parcel.outbox_event_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING'::vietride_parcel.outbox_event_status, 'PUBLISHING'::vietride_parcel.outbox_event_status, 'FAILED'::vietride_parcel.outbox_event_status)");

                    b.ToTable("outbox_events", "vietride_parcel");
                });
#pragma warning restore 612, 618
        }
    }
}
