namespace VietRide.Parcel.Domain.Enums;

public enum ParcelStatus
{
    PENDING_OPERATOR_REVIEW,
    PENDING_PAYMENT,
    PENDING,
    PENDING_ADDITIONAL_PAYMENT,
    RESERVED,
    CHECKED_IN,
    PENDING_FINAL_PAYMENT,
    READY_TO_LOAD,
    LOADED,
    IN_TRANSIT,
    PENDING_TRANSFER_CONFIRM,
    TRANSFER_ESCALATED,
    UNLOADED,
    DELIVERED_PENDING_CONFIRM,
    DELIVERY_CONFIRMED,
    DELIVERY_REJECTED,
    RETURN_INITIATED,
    RETURNED,
    PENDING_OPERATOR_ACTION,
    CANCELLED,
    REJECTED,
    EXPIRED,
}
