<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\libs\dotnet\VietRide.Shared.Kernel\VietRide.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\..\libs\dotnet\VietRide.Shared.Persistence\VietRide.Shared.Persistence.csproj" />
    <ProjectReference Include="..\..\src\VietRide.Identity.Domain\VietRide.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\VietRide.Identity.Application\VietRide.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\VietRide.Identity.Infrastructure\VietRide.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\VietRide.Identity.Api\VietRide.Identity.Api.csproj" />
  </ItemGroup>

</Project>
