// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Trip.Infrastructure;

#nullable disable

namespace VietRide.Trip.Infrastructure.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20260707093000_FixFreshDbOutboxEnumSchema")]
    partial class FixFreshDbOutboxEnumSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_trip")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_trip", "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_generation_skip_reason", new[] { "SUBSCRIPTION_LIMIT_EXCEEDED", "VEHICLE_CONFLICT", "DRIVER_CONFLICT", "OTHER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_seat_status", new[] { "AVAILABLE", "HELD", "BOOKED", "UNAVAILABLE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_seat_type", new[] { "STANDARD", "SLEEPER_LOWER", "SLEEPER_UPPER", "VIP", "DRIVER_AREA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_source", new[] { "MANUAL", "AUTO_FROM_SCHEDULE", "VEHICLE_SUBSTITUTION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_status", new[] { "SCHEDULED", "BOARDING", "IN_PROGRESS", "COMPLETED", "CANCELLED", "DISRUPTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_stop_status", new[] { "PENDING", "ARRIVED", "SKIPPED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
