// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Shared.Persistence.Outbox;
using VietRide.Trip.Infrastructure;

#nullable disable

namespace VietRide.Trip.Infrastructure.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_trip")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<OutboxEventStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("outbox_event_status")
                        .HasDefaultValue(OutboxEventStatus.PENDING)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING', 'PUBLISHING', 'FAILED')");

                    b.ToTable("outbox_events", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.AlternativeRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_station_id");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<decimal?>("TotalDistanceKm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("total_distance_km");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_alternative_routes");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("idx_alternative_routes_route_id")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("alternative_routes", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.AlternativeRouteStop", b =>
                {
                    b.Property<Guid>("AlternativeRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("alternative_route_id");

                    b.Property<Guid>("StopId")
                        .HasColumnType("uuid")
                        .HasColumnName("stop_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DistanceFromOriginKm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("distance_from_origin_km");

                    b.Property<int>("EstimatedDurationFromOriginMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_from_origin_minutes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AlternativeRouteId", "StopId")
                        .HasName("pk_alternative_route_stops");

                    b.HasIndex("AlternativeRouteId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("uq_alternative_route_stops_route_order");

                    b.ToTable("alternative_route_stops", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_alternative_route_stops_order_positive", "order_index > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.DriverSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssistantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonElement>("DayOfWeek")
                        .HasColumnType("jsonb")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("departure_time");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_schedules");

                    b.HasIndex("DriverUserId", "IsActive")
                        .HasDatabaseName("idx_driver_schedules_driver_active");

                    b.HasIndex("OperatorId", "IsActive")
                        .HasDatabaseName("idx_driver_schedules_operator_active");

                    b.HasIndex("RouteId", "IsActive")
                        .HasDatabaseName("idx_driver_schedules_route_active");

                    b.HasIndex("VehicleId", "IsActive")
                        .HasDatabaseName("idx_driver_schedules_vehicle_active")
                        .HasFilter("vehicle_id IS NOT NULL");

                    b.ToTable("driver_schedules", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_driver_schedules_valid_until_after_from", "valid_until IS NULL OR valid_until >= valid_from");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.OperatorStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CounterLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("counter_location");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayNameOverride")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name_override");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_operator_stations");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_operator_stations_operator_id")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("StationId")
                        .HasDatabaseName("idx_operator_stations_station_id")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("OperatorId", "StationId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_stations_operator_station");

                    b.ToTable("operator_stations", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("BaseFare")
                        .HasColumnType("bigint")
                        .HasColumnName("base_fare");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DestinationStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_station_id");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("OriginStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_station_id");

                    b.Property<Guid?>("ReturnRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_route_id");

                    b.Property<decimal?>("TotalDistanceKm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("total_distance_km");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_routes_operator_id")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("ReturnRouteId")
                        .HasDatabaseName("idx_routes_return_route_id")
                        .HasFilter("return_route_id IS NOT NULL");

                    b.HasIndex("OriginStationId", "DestinationStationId")
                        .HasDatabaseName("idx_routes_origin_destination")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("routes", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_routes_base_fare_non_negative", "base_fare >= 0");

                            t.HasCheckConstraint("chk_routes_origin_dest_different", "origin_station_id <> destination_station_id");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("StopId")
                        .HasColumnType("uuid")
                        .HasColumnName("stop_id");

                    b.Property<bool>("AllowDropoff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_dropoff");

                    b.Property<bool>("AllowPickup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_pickup");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DistanceFromOriginKm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("distance_from_origin_km");

                    b.Property<int>("EstimatedDurationFromOriginMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_from_origin_minutes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RouteId", "StopId")
                        .HasName("pk_route_stops");

                    b.HasIndex("StopId")
                        .HasDatabaseName("idx_route_stops_stop_id");

                    b.HasIndex("RouteId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("uq_route_stops_route_order");

                    b.ToTable("route_stops", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_route_stops_allow_at_least_one", "allow_pickup = TRUE OR allow_dropoff = TRUE");

                            t.HasCheckConstraint("chk_route_stops_order_positive", "order_index > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.RouteStopFareTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<long>("FareFromThisStop")
                        .HasColumnType("bigint")
                        .HasColumnName("fare_from_this_stop");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("StopId")
                        .HasColumnType("uuid")
                        .HasColumnName("stop_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_route_stop_fare_templates");

                    b.HasIndex("RouteId", "StopId", "EffectiveFrom")
                        .HasDatabaseName("idx_route_stop_fare_templates_route_stop_effective");

                    b.ToTable("route_stop_fare_templates", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_route_stop_fare_templates_effective_order", "effective_until IS NULL OR effective_until > effective_from");

                            t.HasCheckConstraint("chk_route_stop_fare_templates_fare_non_negative", "fare_from_this_stop >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_street");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<JsonElement?>("Facilities")
                        .HasColumnType("jsonb")
                        .HasColumnName("facilities");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonElement?>("OperatingHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("operating_hours");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<bool>("SupportsShuttle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_shuttle");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_stations_name_trgm")
                        .HasFilter("FALSE");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_stations_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SupportsShuttle")
                        .HasDatabaseName("idx_stations_supports_shuttle")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("City", "Province")
                        .HasDatabaseName("idx_stations_city_province")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("stations", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_place_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid?>("ReplacedByStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_stop_id");

                    b.Property<bool>("SharedSuggestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("shared_suggestion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_stops");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_stops_operator_id")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("ReplacedByStopId")
                        .HasDatabaseName("idx_stops_replaced_by")
                        .HasFilter("replaced_by_stop_id IS NOT NULL");

                    b.HasIndex("SharedSuggestion")
                        .HasDatabaseName("idx_stops_shared_suggestion")
                        .HasFilter("shared_suggestion = TRUE AND is_active = TRUE");

                    b.ToTable("stops", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_stops_no_self_replacement", "replaced_by_stop_id IS NULL OR replaced_by_stop_id <> id");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ActualDepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_departure_time");

                    b.Property<Guid?>("AssistantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_user_id");

                    b.Property<long>("BaseFare")
                        .HasColumnType("bigint")
                        .HasColumnName("base_fare");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DepartureDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date_time");

                    b.Property<DateTimeOffset?>("DisruptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disrupted_at");

                    b.Property<string>("DisruptionReason")
                        .HasColumnType("text")
                        .HasColumnName("disruption_reason");

                    b.Property<Guid?>("DriverScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_schedule_id");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_user_id");

                    b.Property<DateTimeOffset>("EstimatedArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_arrival_time");

                    b.Property<decimal>("EstimatedPassengerLuggageKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estimated_passenger_luggage_kg");

                    b.Property<bool>("HasSubstitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_substitution");

                    b.Property<decimal?>("MaxCargoWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_cargo_weight_kg");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<decimal>("ReservedParcelWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("reserved_parcel_weight_kg");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("trip_source")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("trip_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'SCHEDULED'::trip_status");

                    b.Property<decimal>("TotalLoadedWeightKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_loaded_weight_kg");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("AssistantUserId")
                        .HasDatabaseName("idx_trips_assistant_user_id")
                        .HasFilter("assistant_user_id IS NOT NULL");

                    b.HasIndex("DriverScheduleId")
                        .HasDatabaseName("idx_trips_driver_schedule_id")
                        .HasFilter("driver_schedule_id IS NOT NULL");

                    b.HasIndex("DriverUserId", "DepartureDateTime")
                        .IsUnique()
                        .HasDatabaseName("uq_trips_driver_departure")
                        .HasFilter("status NOT IN ('CANCELLED')");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_trips_operator_status");

                    b.HasIndex("RouteId", "DepartureDateTime")
                        .HasDatabaseName("idx_trips_route_departure");

                    b.HasIndex("Status", "DepartureDateTime")
                        .HasDatabaseName("idx_trips_status_departure");

                    b.HasIndex("VehicleId", "DepartureDateTime")
                        .IsUnique()
                        .HasDatabaseName("uq_trips_vehicle_departure")
                        .HasFilter("status NOT IN ('CANCELLED')");

                    b.ToTable("trips", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_trips_base_fare_non_negative", "base_fare >= 0");

                            t.HasCheckConstraint("chk_trips_cargo_counters_non_negative", "reserved_parcel_weight_kg >= 0 AND total_loaded_weight_kg >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.TripSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("text")
                        .HasColumnName("disabled_reason");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("trip_seat_type")
                        .HasColumnName("seat_type")
                        .HasDefaultValueSql("'STANDARD'::trip_seat_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("trip_seat_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'AVAILABLE'::trip_seat_status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_trip_seats");

                    b.HasIndex("TripId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_trip_seats_trip_seat");

                    b.HasIndex("TripId", "Status")
                        .HasDatabaseName("idx_trip_seats_trip_status");

                    b.ToTable("trip_seats", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<decimal?>("MaxCargoVolumeM3")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_cargo_volume_m3");

                    b.Property<decimal?>("MaxCargoWeightKg")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("max_cargo_weight_kg");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<JsonElement>("SeatLayoutJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("seat_layout_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vehicle_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::vehicle_status");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_type_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_license_plate")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("VehicleTypeId")
                        .HasDatabaseName("idx_vehicles_vehicle_type_id");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_vehicles_operator_status")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("vehicles", "vietride_trip", t =>
                        {
                            t.HasCheckConstraint("chk_vehicles_cargo_weight_non_negative", "max_cargo_weight_kg IS NULL OR max_cargo_weight_kg >= 0");

                            t.HasCheckConstraint("chk_vehicles_total_seats_positive", "total_seats > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DefaultSeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("default_seat_count");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<int?>("EstimatedPassengerLuggageKgPerSeat")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_passenger_luggage_kg_per_seat");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemDefined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_defined");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicle_types_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_vehicle_types_is_active");

                    b.ToTable("vehicle_types", "vietride_trip");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.AlternativeRoute", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.AlternativeRouteStop", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.AlternativeRoute", null)
                        .WithMany()
                        .HasForeignKey("AlternativeRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Stop", null)
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.DriverSchedule", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.OperatorStation", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Route", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("DestinationStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("OriginStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("ReturnRouteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Stop", null)
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.RouteStopFareTemplate", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Stop", null)
                        .WithMany()
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Stop", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.Stop", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByStopId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.TripEntity", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.DriverSchedule", null)
                        .WithMany()
                        .HasForeignKey("DriverScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VietRide.Trip.Domain.Entities.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietRide.Trip.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.TripSeat", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.TripEntity", null)
                        .WithMany("Seats")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_seats_trips_trip_entity_id");
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VietRide.Trip.Domain.Entities.VehicleType", null)
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VietRide.Trip.Domain.Entities.TripEntity", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
