export const ENV_TOKEN = Symbol('ENV_TOKEN');
export const TRACKING_JWT_VERIFIER = Symbol('TRACKING_JWT_VERIFIER');
export const TRACKING_AUTHORIZATION_ADAPTER = Symbol('TRACKING_AUTHORIZATION_ADAPTER');
