namespace VietRide.Booking.Domain.Enums;

public enum BookingCancellationReason
{
    USER_INITIATED,
    OPERATOR_CANCELLED_TRIP,
    OPERATOR_DISRUPTED_IN_PROGRESS,
    SCHEDULE_CHANGED,
    ROUTE_CHANGED_REFUSED,
    VEHICLE_SUBSTITUTION_DOWNGRADE,
    VEHICLE_SUBSTITUTION_NO_SEAT,
    STOP_DISABLED_REFUSED,
}
