// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Booking.Infrastructure;

#nullable disable

namespace VietRide.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_booking")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_cancellation_reason", new[] { "USER_INITIATED", "OPERATOR_CANCELLED_TRIP", "OPERATOR_DISRUPTED_IN_PROGRESS", "SCHEDULE_CHANGED", "ROUTE_CHANGED_REFUSED", "VEHICLE_SUBSTITUTION_DOWNGRADE", "VEHICLE_SUBSTITUTION_NO_SEAT", "STOP_DISABLED_REFUSED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_pending_action_reason", new[] { "ROUTE_CHANGE", "SEAT_DOWNGRADE", "SCHEDULE_CHANGE", "PENDING_SEAT_ASSIGNMENT", "STOP_DISABLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_pending_action_resolved", new[] { "ACCEPTED", "REJECTED", "AUTO_FALLBACK_DESTINATION", "AUTO_CANCELLED_NO_SEAT", "OPERATOR_RESOLVED", "SUPERSEDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_pending_action_severity", new[] { "MEDIUM", "MAJOR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "PENDING_PAYMENT", "CONFIRMED", "COMPLETED", "EXPIRED", "CANCELLED", "NO_SHOW", "PARTIAL_NO_SHOW", "REFUNDED", "DISRUPTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "operator_voucher_consent_status", new[] { "PENDING", "ACCEPTED", "REJECTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_boarding_status", new[] { "PENDING", "BOARDED", "NO_SHOW" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "ticket_status", new[] { "PENDING_PAYMENT", "ISSUED", "USED", "CANCELLED", "REFUNDED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_direction", new[] { "OUTBOUND", "RETURN" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_booking", "booking_transfer_confirmation_status", new[] { "PENDING_CONFIRM", "CONFIRMED", "NOT_REQUIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_booking", "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "voucher_funding_type", new[] { "VIETRIDE_FUNDED", "OPERATOR_FUNDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "voucher_type", new[] { "PERCENT_OFF", "FIXED_AMOUNT" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("BaseFare")
                        .HasColumnType("bigint")
                        .HasColumnName("base_fare");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("booking_code");

                    b.Property<Guid?>("BookingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_id");

                    b.Property<string>("BuyerAvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("buyer_avatar_url");

                    b.Property<string>("BuyerDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_display_name");

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("buyer_phone");

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("booking_cancellation_reason")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("DropoffStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropoff_station_id");

                    b.Property<Guid?>("DropoffStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropoff_stop_id");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("PassengerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_user_id");

                    b.Property<Guid?>("PickupStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_station_id");

                    b.Property<Guid?>("PickupStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_stop_id");

                    b.Property<bool>("RefundOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("refund_override");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<Guid?>("SeatLockToken")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_lock_token");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("booking_status")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("TripCurrentDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_current_departure");

                    b.Property<int?>("TripDirection")
                        .HasColumnType("trip_direction")
                        .HasColumnName("trip_direction");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("TripSnapshotDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_snapshot_departure");

                    b.Property<string>("TripSnapshotDestName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("trip_snapshot_dest_name");

                    b.Property<string>("TripSnapshotOriginName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("trip_snapshot_origin_name");

                    b.Property<string>("TripSnapshotRouteName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("trip_snapshot_route_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("BookingCode")
                        .IsUnique()
                        .HasDatabaseName("uq_bookings_booking_code");

                    b.HasIndex("BookingGroupId")
                        .HasDatabaseName("idx_bookings_booking_group_id")
                        .HasFilter("booking_group_id IS NOT NULL");

                    b.HasIndex("TripCurrentDeparture")
                        .IsDescending()
                        .HasDatabaseName("idx_bookings_trip_current_departure");

                    b.HasIndex("TripSnapshotDeparture")
                        .HasDatabaseName("idx_bookings_trip_snapshot_departure");

                    b.HasIndex("CompletedAt", "OperatorId")
                        .HasDatabaseName("idx_bookings_completed_report")
                        .HasFilter("status = 'COMPLETED' AND completed_at IS NOT NULL");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_bookings_operator_id_status");

                    b.HasIndex("PassengerUserId", "CreatedAt")
                        .HasDatabaseName("idx_bookings_passenger_user_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_bookings_status_created_at")
                        .HasFilter("status IN ('PENDING_PAYMENT', 'CONFIRMED')");

                    b.HasIndex("TripId", "Status")
                        .HasDatabaseName("idx_bookings_trip_id_status");

                    b.ToTable("bookings", "vietride_booking", t =>
                        {
                            t.HasCheckConstraint("chk_bookings_amounts_non_negative", "base_fare >= 0 AND discount_amount >= 0 AND total_amount >= 0");

                            t.HasCheckConstraint("chk_bookings_dropoff_at_most_one", "(dropoff_station_id IS NOT NULL)::INT + (dropoff_stop_id IS NOT NULL)::INT <= 1");

                            t.HasCheckConstraint("chk_bookings_pickup_exactly_one", "(pickup_station_id IS NOT NULL)::INT + (pickup_stop_id IS NOT NULL)::INT = 1");

                            t.HasCheckConstraint("chk_bookings_total_le_base", "total_amount <= base_fare");
                        });
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingPendingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Reason")
                        .HasColumnType("booking_pending_action_reason")
                        .HasColumnName("reason");

                    b.Property<int?>("ResolvedAction")
                        .HasColumnType("booking_pending_action_resolved")
                        .HasColumnName("resolved_action");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("Severity")
                        .HasColumnType("booking_pending_action_severity")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_booking_pending_actions");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_pending_actions_active_per_booking")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("idx_booking_pending_actions_deadline_unresolved")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("Reason")
                        .HasDatabaseName("idx_booking_pending_actions_reason");

                    b.ToTable("booking_pending_actions", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingShuttleIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<decimal>("PickupLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal>("PickupLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("pickup_longitude");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_booking_shuttle_intents");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_shuttle_intents_booking");

                    b.ToTable("booking_shuttle_intents", "vietride_booking", t =>
                        {
                            t.HasCheckConstraint("chk_booking_shuttle_intents_latitude", "pickup_latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("chk_booking_shuttle_intents_longitude", "pickup_longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingStationRedirect", b =>
                {
                    b.Property<Guid>("DuplicateStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_station_id");

                    b.Property<Guid>("CanonicalStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_station_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("DuplicateStationId")
                        .HasName("pk_booking_station_redirects");

                    b.HasIndex("CanonicalStationId")
                        .HasDatabaseName("idx_booking_station_redirects_canonical");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_station_redirects_source_event");

                    b.ToTable("booking_station_redirects", "vietride_booking", t =>
                        {
                            t.HasCheckConstraint("chk_booking_station_redirects_not_self", "duplicate_station_id <> canonical_station_id");
                        });
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text")
                        .HasColumnName("operator_name");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<int>("TotalBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bookings");

                    b.Property<int>("TotalCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_cancelled");

                    b.Property<int>("TotalCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_completed");

                    b.Property<int>("TotalConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_confirmed");

                    b.Property<int>("TotalNoShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_no_show");

                    b.Property<long>("TotalRefunded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("total_refunded")
                        .HasDefaultValueSql("0");

                    b.Property<long>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("total_revenue")
                        .HasDefaultValueSql("0");

                    b.Property<int>("TotalSeatsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_seats_booked");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_booking_stats");

                    b.HasIndex("OperatorId", "StatDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_booking_stats_operator_date");

                    b.ToTable("booking_stats", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingStatsProcessedEvent", b =>
                {
                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EventType", "BookingId")
                        .HasName("pk_booking_stats_processed_events");

                    b.ToTable("booking_stats_processed_events", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("booking_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_history");

                    b.HasIndex("BookingId", "OccurredAt", "Id")
                        .HasDatabaseName("idx_booking_status_history_booking_occurred_id");

                    b.ToTable("booking_status_history", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("vietride_booking.booking_transfer_confirmation_status")
                        .HasColumnName("confirmation_status");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NewSeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("new_seat_number");

                    b.Property<Guid>("NewTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_trip_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OriginalSeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_seat_number");

                    b.Property<Guid>("OriginalTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_trip_id");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("TransferredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transferred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TransferredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferred_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_transfers");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_booking_transfers_booking_id");

                    b.HasIndex("NewTripId")
                        .HasDatabaseName("idx_booking_transfers_new_trip_id");

                    b.HasIndex("OriginalTripId")
                        .HasDatabaseName("idx_booking_transfers_original_trip_id");

                    b.HasIndex("PassengerId")
                        .HasDatabaseName("idx_booking_transfers_passenger_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("idx_booking_transfers_ticket_id");

                    b.HasIndex("PassengerId", "OriginalTripId", "NewTripId")
                        .IsUnique()
                        .HasDatabaseName("uq_booking_transfers_passenger_trip_pair");

                    b.ToTable("booking_transfers", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_operator_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("OwnerOperatorId")
                        .HasDatabaseName("idx_campaigns_owner_operator")
                        .HasFilter("owner_operator_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("IsActive", "ValidUntil")
                        .HasDatabaseName("idx_campaigns_active_validity");

                    b.ToTable("campaigns", "vietride_booking", t =>
                        {
                            t.HasCheckConstraint("chk_campaigns_validity_window", "valid_until > valid_from");
                        });
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.CampaignVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_vouchers");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("idx_campaign_vouchers_voucher_id");

                    b.HasIndex("CampaignId", "VoucherId")
                        .IsUnique()
                        .HasDatabaseName("uq_campaign_vouchers_campaign_voucher");

                    b.ToTable("campaign_vouchers", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.OperatorVoucherConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid?>("RespondedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responded_by_user_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("operator_voucher_consent_status")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_operator_voucher_consents");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_operator_voucher_consents_status");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("idx_operator_voucher_consents_voucher_id");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_operator_voucher_consents_operator_status");

                    b.HasIndex("OperatorId", "VoucherId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_voucher_consents_operator_voucher");

                    b.ToTable("operator_voucher_consents", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("BoardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("boarded_at");

                    b.Property<Guid?>("BoardedAtStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("boarded_at_stop_id");

                    b.Property<int>("BoardingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("passenger_boarding_status")
                        .HasDefaultValue(0)
                        .HasColumnName("boarding_status");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seat_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_passengers");

                    b.HasIndex("BookingId", "BoardingStatus")
                        .HasDatabaseName("idx_passengers_boarding_status");

                    b.HasIndex("BookingId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_passengers_booking_seat");

                    b.ToTable("passengers", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<long>("FareAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("fare_amount");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<long>("PaidAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("paid_amount");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seat_number");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.ticket_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING_PAYMENT'::public.ticket_status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ticket_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("PassengerId")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_passenger_id");

                    b.HasIndex("SeatNumber")
                        .HasDatabaseName("idx_tickets_seat_number");

                    b.HasIndex("TicketCode")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_ticket_code");

                    b.HasIndex("BookingId", "Status")
                        .HasDatabaseName("idx_tickets_booking_status");

                    b.ToTable("tickets", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<List<Guid>>("ApplicableOperatorIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("applicable_operator_ids");

                    b.Property<List<string>>("ApplicablePaymentMethods")
                        .HasColumnType("text[]")
                        .HasColumnName("applicable_payment_methods");

                    b.Property<List<Guid>>("ApplicableRouteIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("applicable_route_ids");

                    b.Property<List<string>>("ApplicableServices")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("applicable_services");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FundingType")
                        .HasColumnType("voucher_funding_type")
                        .HasColumnName("funding_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long?>("MaxDiscountAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("max_discount_amount");

                    b.Property<long>("MinOrderAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("min_order_amount")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("NewUserOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("new_user_only");

                    b.Property<Guid?>("OwnerOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_operator_id");

                    b.Property<int?>("PerUserLimit")
                        .HasColumnType("integer")
                        .HasColumnName("per_user_limit");

                    b.Property<int?>("TotalUsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("total_usage_limit");

                    b.Property<int>("Type")
                        .HasColumnType("voucher_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_vouchers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_vouchers_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("NewUserOnly")
                        .HasDatabaseName("idx_vouchers_new_user_only");

                    b.HasIndex("OwnerOperatorId")
                        .HasDatabaseName("idx_vouchers_owner_operator")
                        .HasFilter("owner_operator_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("ValidUntil")
                        .HasDatabaseName("idx_vouchers_active_validity")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("vouchers", "vietride_booking", t =>
                        {
                            t.HasCheckConstraint("chk_vouchers_applicable_payment_methods_valid", "applicable_payment_methods IS NULL OR applicable_payment_methods <@ ARRAY['WALLET', 'VNPAY']::text[]");

                            t.HasCheckConstraint("chk_vouchers_applicable_services_valid", "applicable_services <@ ARRAY['BOOKING', 'PARCEL']::text[] AND cardinality(applicable_services) > 0");

                            t.HasCheckConstraint("chk_vouchers_min_order_non_negative", "min_order_amount >= 0");

                            t.HasCheckConstraint("chk_vouchers_operator_owned_funding", "owner_operator_id IS NULL OR funding_type = 'OPERATOR_FUNDED'::voucher_funding_type");

                            t.HasCheckConstraint("chk_vouchers_validity_window", "valid_until > valid_from");

                            t.HasCheckConstraint("chk_vouchers_value_positive", "value > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.VoucherUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_group_id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DiscountAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount");

                    b.Property<int>("FundedBy")
                        .HasColumnType("voucher_funding_type")
                        .HasColumnName("funded_by");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_voucher_usages");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_voucher_usages_booking_id")
                        .HasFilter("booking_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_voucher_usages_reference");

                    b.HasIndex("VoucherId", "BookingGroupId")
                        .HasDatabaseName("idx_voucher_usages_voucher_group")
                        .HasFilter("booking_group_id IS NOT NULL");

                    b.HasIndex("VoucherId", "UserId")
                        .HasDatabaseName("idx_voucher_usages_voucher_user");

                    b.ToTable("voucher_usages", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Inbox.IntegrationInboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_integration_inbox");

                    b.HasIndex("ConsumerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("uq_integration_inbox_consumer_message");

                    b.ToTable("integration_inbox", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxDlq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("TerminalAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_outbox_dlq");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_outbox_dlq_event_id");

                    b.HasIndex("TerminalAt", "EventId")
                        .IsDescending()
                        .HasDatabaseName("idx_outbox_dlq_terminal_event_id");

                    b.ToTable("outbox_dlq", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_booking.outbox_event_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING'::vietride_booking.outbox_event_status, 'PUBLISHING'::vietride_booking.outbox_event_status, 'FAILED'::vietride_booking.outbox_event_status)");

                    b.ToTable("outbox_events", "vietride_booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingPendingAction", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", "Booking")
                        .WithMany("PendingActions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_pending_actions_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingShuttleIntent", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", "Booking")
                        .WithOne("ShuttleIntent")
                        .HasForeignKey("VietRide.Booking.Domain.Entities.BookingShuttleIntent", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_shuttle_intents_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_bookings_booking_id");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.BookingTransfer", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_transfers_bookings_booking_id");

                    b.HasOne("VietRide.Booking.Domain.Entities.Passenger", null)
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_transfers_passengers_passenger_id");

                    b.HasOne("VietRide.Booking.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_transfers_tickets_ticket_id");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.CampaignVoucher", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Campaign", "Campaign")
                        .WithMany("CampaignVouchers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_vouchers_campaigns_campaign_id");

                    b.HasOne("VietRide.Booking.Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_vouchers_vouchers_voucher_id");

                    b.Navigation("Campaign");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.OperatorVoucherConsent", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operator_voucher_consents_vouchers_voucher_id");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Passenger", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_passengers_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_bookings_booking_id");

                    b.HasOne("VietRide.Booking.Domain.Entities.Passenger", "Passenger")
                        .WithOne("Ticket")
                        .HasForeignKey("VietRide.Booking.Domain.Entities.Ticket", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_passengers_passenger_id");

                    b.Navigation("Booking");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.VoucherUsage", b =>
                {
                    b.HasOne("VietRide.Booking.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_voucher_usages_bookings_booking_id");

                    b.HasOne("VietRide.Booking.Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_usages_vouchers_voucher_id");

                    b.Navigation("Booking");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("PendingActions");

                    b.Navigation("ShuttleIntent");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignVouchers");
                });

            modelBuilder.Entity("VietRide.Booking.Domain.Entities.Passenger", b =>
                {
                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
