// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Identity.Domain.Enums;
using VietRide.Identity.Infrastructure;
using VietRide.Shared.Persistence.Outbox;

#nullable disable

namespace VietRide.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260722093524_CreateIntegrationInboxTable")]
    partial class CreateIntegrationInboxTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_identity")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "activity_log_action", new[] { "LOGIN", "LOGOUT", "BOOK_TICKET", "CANCEL_TICKET", "UPDATE_PROFILE", "CHANGE_PASSWORD", "COMPLETE_PROFILE", "CREATE_OPERATOR", "APPROVE_OPERATOR", "REJECT_OPERATOR", "LOCK_USER", "UNLOCK_USER", "VEHICLE_SUBSTITUTION_TRIGGERED", "DRIVER_SCHEDULE_EDIT", "VEHICLE_SWAP", "TRIP_COMPLETED_MANUAL", "PARCEL_UNLOAD_OVERRIDE", "PARCEL_DELIVERY_RESEND", "PARCEL_MANUAL_CONFIRM", "TRIP_SETTLEMENT_MANUAL", "OPERATOR_WALLET_ADJUSTMENT", "SET_INITIAL_PASSWORD", "RESEND_INITIAL_PASSWORD", "STATION_MERGED", "STATION_NORMALIZED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "device_platform", new[] { "IOS", "ANDROID", "WEB" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "email_verification_purpose", new[] { "REGISTRATION", "PASSWORD_RESET", "SET_INITIAL_PASSWORD" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "oauth_provider", new[] { "GOOGLE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "operator_registration_status", new[] { "PENDING", "APPROVED", "REJECTED", "SUSPENDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "refresh_token_revoke_reason", new[] { "NORMAL_ROTATION", "REUSE_DETECTED", "USER_LOGOUT", "ADMIN_REVOKE", "PASSWORD_RESET" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_billing_period", new[] { "MONTHLY", "YEARLY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_payment_method", new[] { "VNPAY", "WALLET" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_status", new[] { "PENDING_APPROVAL", "ACTIVE", "EXPIRED", "CANCELLED", "PENDING_PAYMENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_upgrade_attempt_status", new[] { "INITIATED", "PAYMENT_PENDING", "SUCCEEDED", "EXPIRED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "PASSENGER", "DRIVER", "ASSISTANT", "OPERATOR_STAFF", "OPERATOR_ADMIN", "SYSTEM_ADMIN" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "PENDING_EMAIL_VERIFICATION", "PENDING_INITIAL_PASSWORD", "ACTIVE", "LOCKED", "DELETED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_identity", "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<ActivityLogAction>("Action")
                        .HasColumnType("activity_log_action")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_logs");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_activity_logs_source_event_id")
                        .HasFilter("source_event_id IS NOT NULL");

                    b.HasIndex("Action", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_logs_action_created_at");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("idx_activity_logs_created_at_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_activity_logs_user_id_created_at");

                    b.ToTable("activity_logs", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<EmailVerificationPurpose>("Purpose")
                        .HasColumnType("email_verification_purpose")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_email_verification_tokens_expires_at")
                        .HasFilter("used_at IS NULL");

                    b.HasIndex("Code", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("uq_email_verification_tokens_code_purpose");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("idx_email_verification_tokens_user_purpose")
                        .HasFilter("used_at IS NULL");

                    b.ToTable("email_verification_tokens", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.OAuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<OAuthProvider>("Provider")
                        .HasColumnType("oauth_provider")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_email");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_oauth_identities_user_id");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("uq_oauth_identities_provider_subject");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("uq_oauth_identities_user_provider");

                    b.ToTable("oauth_identities", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AddressDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_district");

                    b.Property<string>("AddressProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_province");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_street");

                    b.Property<string>("AddressWard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_ward");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_account_name");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BusinessRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_registration_number");

                    b.Property<JsonElement?>("CancellationPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("cancellation_policy")
                        .HasComment("JSONB array of {hoursBeforeDeparture, feePercent}; sorted ascending. NULL = no policy configured.");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<JsonElement?>("LuggagePolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("luggage_policy")
                        .HasComment("JSONB {defaultLuggageKgPerSeat}. NULL defaults to {10}.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonElement?>("ParcelNoShowPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("parcel_no_show_policy")
                        .HasComment("JSONB {noShowFeePercent, additionalPaymentTimeoutMinutes}. NULL defaults to {0, 30}.");

                    b.Property<OperatorRegistrationStatus>("RegistrationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("operator_registration_status")
                        .HasDefaultValue(OperatorRegistrationStatus.PENDING)
                        .HasColumnName("registration_status");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("representative_name");

                    b.Property<string>("RepresentativePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("representative_phone");

                    b.Property<string>("SuspendReason")
                        .HasColumnType("text")
                        .HasColumnName("suspend_reason");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_operators");

                    b.HasIndex("BusinessRegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_operators_business_reg_number")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_operators_is_active");

                    b.HasIndex("RegistrationStatus")
                        .HasDatabaseName("idx_operators_registration_status");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasDatabaseName("uq_operators_tax_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("operators", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.OperatorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<SubscriptionBillingPeriod?>("BillingPeriod")
                        .HasColumnType("subscription_billing_period")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentAssistants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_assistants");

                    b.Property<int>("CurrentDrivers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_drivers");

                    b.Property<int>("CurrentOperatorUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_operator_users");

                    b.Property<int>("CurrentRoutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_routes");

                    b.Property<int>("CurrentTripsThisMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_trips_this_month")
                        .HasComment("Reset to 0 monthly by Hangfire (day 1, 00:01). Skipped for Trip.source = VEHICLE_SUBSTITUTION.");

                    b.Property<int>("CurrentVehicles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_vehicles");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastResetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<SubscriptionPaymentMethod?>("PaymentMethod")
                        .HasColumnType("subscription_payment_method")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_plan_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<SubscriptionStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("subscription_status")
                        .HasDefaultValue(SubscriptionStatus.PENDING_APPROVAL)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TrialExpiringWarnSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_expiring_warn_sent_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_operator_subscriptions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_operator_subscriptions_expires_at")
                        .HasFilter("status = 'ACTIVE'");

                    b.HasIndex("OperatorId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_subscriptions_operator_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("idx_operator_subscriptions_active_plan_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_operator_subscriptions_status");

                    b.ToTable("operator_subscriptions", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.OperatorWalletBackfillMarker", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OperatorId")
                        .HasName("pk_operator_wallet_backfill_markers");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_operator_wallet_backfill_markers_event_id");

                    b.ToTable("operator_wallet_backfill_markers", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<RefreshTokenRevokeReason?>("RevokedReason")
                        .HasColumnType("refresh_token_revoke_reason")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_expires_at")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family_id");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("idx_refresh_tokens_parent_token_id")
                        .HasFilter("parent_token_id IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EnableParcel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enable_parcel");

                    b.Property<bool>("EnableRag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enable_rag");

                    b.Property<bool>("EnableShuttle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enable_shuttle");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxAssistants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_assistants");

                    b.Property<int>("MaxDrivers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_drivers");

                    b.Property<int>("MaxOperatorUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_operator_users");

                    b.Property<int>("MaxRoutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_routes");

                    b.Property<int>("MaxTripsPerMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_trips_per_month");

                    b.Property<int>("MaxVehicles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_vehicles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("PricePerMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("price_per_month")
                        .HasDefaultValueSql("0");

                    b.Property<long>("PricePerYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("price_per_year")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_subscription_plans_is_active");

                    b.ToTable("subscription_plans", "vietride_identity", t =>
                        {
                            t.HasCheckConstraint("chk_subscription_plans_price_per_month_non_negative", "price_per_month >= 0");

                            t.HasCheckConstraint("chk_subscription_plans_price_per_year_non_negative", "price_per_year >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.SubscriptionQuotaAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resource");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_subscription_quota_allocations");

                    b.HasIndex("OperatorId", "Resource", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("uq_subscription_quota_allocations_resource");

                    b.HasIndex("SubscriptionId", "Resource", "ReleasedAt")
                        .HasDatabaseName("idx_subscription_quota_allocations_subscription_resource");

                    b.ToTable("subscription_quota_allocations", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.SubscriptionUpgradeAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<SubscriptionBillingPeriod>("BillingPeriod")
                        .HasColumnType("subscription_billing_period")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("FallbackPolicy")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("fallback_policy");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LatestPaymentStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("latest_payment_status");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_payment_id");

                    b.Property<int>("PaymentSessionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("payment_session_version");

                    b.Property<SubscriptionUpgradeAttemptStatus>("Status")
                        .HasColumnType("subscription_upgrade_attempt_status")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TargetPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_subscription_upgrade_attempts");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_subscription_upgrade_attempts_idempotency_key");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("ix_subscription_upgrade_attempts_operator_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_subscription_upgrade_attempts_latest_payment_id")
                        .HasFilter("latest_payment_id IS NOT NULL");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("uq_subscription_upgrade_attempts_active_subscription")
                        .HasFilter("status IN ('INITIATED', 'PAYMENT_PENDING')");

                    b.HasIndex("TargetPlanId")
                        .HasDatabaseName("ix_subscription_upgrade_attempts_target_plan_id");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("idx_subscription_upgrade_attempts_status_due_at");

                    b.ToTable("subscription_upgrade_attempts", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTimeOffset?>("LastFailedLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failed_login_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<UserStatus?>("LockedFromStatus")
                        .HasColumnType("user_status")
                        .HasColumnName("locked_from_status");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<UserStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("user_status")
                        .HasDefaultValue(UserStatus.PENDING_EMAIL_VERIFICATION)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_users_operator_id")
                        .HasFilter("operator_id IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("uq_users_phone")
                        .HasFilter("deleted_at IS NULL AND phone IS NOT NULL");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("idx_users_role_status");

                    b.ToTable("users", "vietride_identity", t =>
                        {
                            t.HasCheckConstraint("chk_users_locked_from_status", "((status = 'LOCKED' AND locked_from_status IN ('ACTIVE', 'PENDING_EMAIL_VERIFICATION')) OR (status <> 'LOCKED' AND locked_from_status IS NULL))");

                            t.HasCheckConstraint("chk_users_operator_role", "(role IN ('DRIVER', 'ASSISTANT', 'OPERATOR_STAFF', 'OPERATOR_ADMIN') AND operator_id IS NOT NULL) OR (role IN ('PASSENGER', 'SYSTEM_ADMIN') AND operator_id IS NULL)");

                            t.HasCheckConstraint("chk_users_phone_format", "phone IS NULL OR phone ~ '^\\+84[0-9]{9,10}$'");
                        });
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DevicePlatform>("Platform")
                        .HasColumnType("device_platform")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("FcmToken")
                        .HasDatabaseName("idx_user_devices_fcm_token")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("LastActiveAt")
                        .HasDatabaseName("idx_user_devices_last_active_at")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_devices_user_active")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("UserId", "FcmToken")
                        .IsUnique()
                        .HasDatabaseName("uq_user_devices_user_fcm_token");

                    b.ToTable("user_devices", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Inbox.IntegrationInboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_integration_inbox");

                    b.HasIndex("ConsumerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("uq_integration_inbox_consumer_message");

                    b.ToTable("integration_inbox", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxDlq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("TerminalAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_outbox_dlq");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_outbox_dlq_event_id");

                    b.HasIndex("TerminalAt", "EventId")
                        .IsDescending()
                        .HasDatabaseName("idx_outbox_dlq_terminal_event_id");

                    b.ToTable("outbox_dlq", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<OutboxEventStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_identity.outbox_event_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING'::vietride_identity.outbox_event_status, 'PUBLISHING'::vietride_identity.outbox_event_status, 'FAILED'::vietride_identity.outbox_event_status)");

                    b.ToTable("outbox_events", "vietride_identity");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_users_user_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_user_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.OAuthIdentity", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_identities_user_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.OperatorSubscription", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operator_subscriptions_operator_id");

                    b.HasOne("VietRide.Identity.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operator_subscriptions_plan_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_parent_token_id");

                    b.HasOne("VietRide.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.SubscriptionQuotaAllocation", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.OperatorSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_quota_allocations_subscription_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.SubscriptionUpgradeAttempt", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_upgrade_attempts_operator_id");

                    b.HasOne("VietRide.Identity.Domain.Entities.OperatorSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_upgrade_attempts_subscription_id");

                    b.HasOne("VietRide.Identity.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("TargetPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_upgrade_attempts_target_plan_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.User", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_operator_id");
                });

            modelBuilder.Entity("VietRide.Identity.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("VietRide.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
