// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Payment.Domain.Enums;
using VietRide.Payment.Infrastructure;

#nullable disable

namespace VietRide.Payment.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260903071427_ReconcileParcelCompensationPayout")]
    partial class ReconcileParcelCompensationPayout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_payment")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "invoice_pdf_generation_status", new[] { "PENDING", "PROCESSING", "FAILED", "COMPLETED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "invoice_status", new[] { "DRAFT", "ISSUED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_ledger_adjustment_reason", new[] { "VIETRIDE_FUNDED_VOUCHER_REVERSAL", "GENERIC_BOOKING_REFUND_ENTITLEMENT", "MANUAL_WALLET_ADJUSTMENT", "LEGACY_UNCLASSIFIED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_ledger_entry_type", new[] { "BOOKING_REVENUE", "PARCEL_REVENUE", "BOOKING_REFUND", "PARCEL_REFUND", "VOUCHER_VIETRIDE_FUNDED_CREDIT", "VOUCHER_OPERATOR_FUNDED_AUDIT", "ADJUSTMENT", "PARCEL_COMPENSATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_ledger_reference_type", new[] { "BOOKING", "PARCEL", "VOUCHER_USAGE", "MANUAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_trip_settlement_method", new[] { "AUTO_WEEKLY", "ADMIN_MANUAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_trip_settlement_status", new[] { "PENDING_HOLD", "ELIGIBLE", "SETTLED", "CANCELLED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_wallet_transaction_ref", new[] { "TRIP_SETTLEMENT", "ADJUSTMENT", "SUBSCRIPTION_PAYMENT", "PARCEL_COMPENSATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "operator_wallet_transaction_type", new[] { "CREDIT", "DEBIT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "payment_method", new[] { "WALLET", "VNPAY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "payment_reference_type", new[] { "BOOKING", "BOOKING_GROUP", "PARCEL", "TOP_UP", "SUBSCRIPTION", "PARCEL_ADDITIONAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "payment_status", new[] { "PENDING_REDIRECT", "SUCCEEDED", "FAILED", "EXPIRED", "REFUNDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "platform_wallet_transaction_link_type", new[] { "BOOKING", "PARCEL", "TRIP_SETTLEMENT", "SUBSCRIPTION", "PARCEL_CLAIM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "platform_wallet_transaction_ref", new[] { "BOOKING_PAYMENT_HOLD", "PARCEL_PAYMENT_HOLD", "PARCEL_ADDITIONAL_PAYMENT_HOLD", "BOOKING_REFUND", "PARCEL_REFUND", "TRIP_SETTLEMENT", "SUBSCRIPTION_PAYMENT", "MANUAL_ADJUSTMENT", "PARCEL_COMPENSATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "platform_wallet_transaction_type", new[] { "CREDIT", "DEBIT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "top_up_request_status", new[] { "PENDING", "SUCCEEDED", "FAILED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "vnpay_return_mode", new[] { "OPERATOR_WEB", "MOBILE_SDK" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "wallet_transaction_ref", new[] { "TOP_UP", "BOOKING_PAYMENT", "BOOKING_REFUND", "PARCEL_PAYMENT", "PARCEL_REFUND", "MANUAL_ADJUSTMENT", "PARCEL_ADDITIONAL_PAYMENT", "PARCEL_COMPENSATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vietride_payment", "wallet_transaction_type", new[] { "CREDIT", "DEBIT" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.DeletedFinancialActorMarker", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_deleted_financial_actor_markers");

                    b.ToTable("deleted_financial_actor_markers", "vietride_payment");
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("OperatorSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_subscription_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<int>("PdfGenerationAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pdf_generation_attempts");

                    b.Property<string>("PdfGenerationLastError")
                        .HasColumnType("text")
                        .HasColumnName("pdf_generation_last_error");

                    b.Property<DateTimeOffset?>("PdfGenerationNextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_generation_next_retry_at");

                    b.Property<DateTimeOffset?>("PdfGenerationStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_generation_started_at");

                    b.Property<InvoicePdfGenerationStatus>("PdfGenerationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_payment.invoice_pdf_generation_status")
                        .HasColumnName("pdf_generation_status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<DateTimeOffset>("PeriodFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_from");

                    b.Property<DateTimeOffset>("PeriodTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_to");

                    b.Property<InvoiceStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_payment.invoice_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'DRAFT'");

                    b.Property<string>("StorageObjectPath")
                        .HasColumnType("text")
                        .HasColumnName("storage_object_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_invoices_invoice_number");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("uq_invoices_payment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoices_status");

                    b.HasIndex("OperatorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_invoices_operator_id_created_at");

                    b.HasIndex("PdfGenerationStatus", "PdfGenerationNextRetryAt")
                        .HasDatabaseName("idx_invoices_pdf_retry")
                        .HasFilter("pdf_generation_status IN ('PENDING', 'FAILED', 'PROCESSING')");

                    b.ToTable("invoices", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_invoices_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("chk_invoices_issued_consistency", "status <> 'ISSUED' OR (issued_at IS NOT NULL AND pdf_url IS NOT NULL AND storage_object_path IS NOT NULL AND pdf_generation_status = 'COMPLETED')");

                            t.HasCheckConstraint("chk_invoices_pdf_attempts", "pdf_generation_attempts >= 0 AND pdf_generation_attempts <= 5");

                            t.HasCheckConstraint("chk_invoices_period_order", "period_to > period_from");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.InvoiceNumberCounter", b =>
                {
                    b.Property<string>("PeriodKey")
                        .HasColumnType("char(6)")
                        .HasColumnName("period_key");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("PeriodKey")
                        .HasName("pk_invoice_number_counters");

                    b.ToTable("invoice_number_counters", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_invoice_number_counters_range", "last_value >= 0 AND last_value <= 999999");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.OperatorLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<bool>("ActorSnapshotResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actor_snapshot_resolved");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type")
                        .HasDefaultValueSql("'SYSTEM'");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<OperatorLedgerAdjustmentReason?>("AdjustmentReason")
                        .HasColumnType("vietride_payment.operator_ledger_adjustment_reason")
                        .HasColumnName("adjustment_reason");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<OperatorLedgerEntryType>("EntryType")
                        .HasColumnType("vietride_payment.operator_ledger_entry_type")
                        .HasColumnName("entry_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("OperatorFundedVoucherAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_funded_voucher_amount");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_code");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<OperatorLedgerReferenceType>("ReferenceType")
                        .HasColumnType("vietride_payment.operator_ledger_reference_type")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_operator_ledger_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("idx_operator_ledger_entries_actor_user_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("OperatorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_operator_ledger_entries_operator_id_created_at");

                    b.HasIndex("OperatorId", "EntryType")
                        .HasDatabaseName("idx_operator_ledger_entries_entry_type");

                    b.HasIndex("OperatorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_operator_ledger_entries_operator_occurred_at")
                        .HasFilter("occurred_at IS NOT NULL");

                    b.HasIndex("OperatorId", "ReferenceCode")
                        .HasDatabaseName("idx_operator_ledger_entries_operator_reference_code")
                        .HasFilter("reference_code IS NOT NULL");

                    b.HasIndex("OperatorId", "TripId")
                        .HasDatabaseName("idx_operator_ledger_entries_operator_trip")
                        .HasFilter("trip_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_operator_ledger_entries_reference");

                    b.HasIndex("CreatedAt", "OperatorId", "ReferenceType")
                        .HasDatabaseName("idx_operator_ledger_entries_canonical_revenue")
                        .HasFilter("entry_type IN ('BOOKING_REVENUE','BOOKING_REFUND','PARCEL_REVENUE','PARCEL_REFUND','VOUCHER_VIETRIDE_FUNDED_CREDIT') OR (entry_type = 'ADJUSTMENT' AND adjustment_reason = 'VIETRIDE_FUNDED_VOUCHER_REVERSAL')");

                    b.HasIndex("SourceEventId", "EntryType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_ledger_entries_source");

                    b.ToTable("operator_ledger_entries", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_operator_ledger_entries_actor_type", "actor_type IN ('USER','SYSTEM')");

                            t.HasCheckConstraint("chk_operator_ledger_entries_adjustment_reason_presence", "(entry_type = 'ADJUSTMENT' AND adjustment_reason IS NOT NULL) OR (entry_type <> 'ADJUSTMENT' AND adjustment_reason IS NULL)");

                            t.HasCheckConstraint("chk_operator_ledger_entries_adjustment_reason_semantics", "(adjustment_reason = 'VIETRIDE_FUNDED_VOUCHER_REVERSAL' AND amount < 0 AND reference_type IN ('BOOKING','PARCEL')) OR (adjustment_reason = 'GENERIC_BOOKING_REFUND_ENTITLEMENT' AND amount = 0 AND reference_type = 'BOOKING') OR (adjustment_reason = 'MANUAL_WALLET_ADJUSTMENT' AND amount <> 0 AND reference_type = 'MANUAL') OR (adjustment_reason = 'LEGACY_UNCLASSIFIED') OR adjustment_reason IS NULL");

                            t.HasCheckConstraint("chk_operator_ledger_entries_amount_direction", "(entry_type IN ('BOOKING_REFUND','PARCEL_REFUND','PARCEL_COMPENSATION') AND amount < 0) OR (entry_type = 'VOUCHER_OPERATOR_FUNDED_AUDIT' AND amount = 0) OR (entry_type = 'ADJUSTMENT') OR (entry_type NOT IN ('BOOKING_REFUND','PARCEL_REFUND','PARCEL_COMPENSATION','VOUCHER_OPERATOR_FUNDED_AUDIT','ADJUSTMENT') AND amount > 0)");

                            t.HasCheckConstraint("chk_operator_ledger_entries_operator_funded_voucher_amount", "operator_funded_voucher_amount IS NULL OR (entry_type = 'VOUCHER_OPERATOR_FUNDED_AUDIT' AND operator_funded_voucher_amount > 0)");

                            t.HasCheckConstraint("chk_operator_ledger_entries_trip_required", "entry_type = 'ADJUSTMENT' OR trip_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.OperatorTripSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActiveFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("active_failure_code");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EligibleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligible_at");

                    b.Property<DateTimeOffset?>("FailureResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failure_resolved_at");

                    b.Property<DateTimeOffset?>("LastSettlementFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_settlement_failure_at");

                    b.Property<long>("NetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("net_amount");

                    b.Property<string>("OperatorContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operator_contact_phone");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorLogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("operator_logo_url");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_name");

                    b.Property<bool>("OperatorSnapshotResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("operator_snapshot_resolved");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("SettledByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("settled_by_display_name");

                    b.Property<string>("SettledByEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("settled_by_email");

                    b.Property<string>("SettledByRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("settled_by_role");

                    b.Property<bool>("SettledBySnapshotResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("settled_by_snapshot_resolved");

                    b.Property<Guid?>("SettledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("settled_by_user_id");

                    b.Property<string>("SettlementCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("settlement_code");

                    b.Property<int>("SettlementFailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("settlement_failure_count");

                    b.Property<OperatorTripSettlementMethod?>("SettlementMethod")
                        .HasColumnType("vietride_payment.operator_trip_settlement_method")
                        .HasColumnName("settlement_method");

                    b.Property<OperatorTripSettlementStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_payment.operator_trip_settlement_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING_HOLD'");

                    b.Property<string>("TripCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trip_code");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("TripTerminalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_terminal_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_operator_trip_settlements");

                    b.HasIndex("SettledAt")
                        .HasDatabaseName("idx_operator_trip_settlements_settled_at")
                        .HasFilter("status = 'SETTLED'");

                    b.HasIndex("SettledByUserId")
                        .HasDatabaseName("idx_operator_trip_settlements_settled_by_user_id")
                        .HasFilter("settled_by_user_id IS NOT NULL");

                    b.HasIndex("SettlementCode")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_trip_settlements_code")
                        .HasFilter("settlement_code IS NOT NULL");

                    b.HasIndex("TripCode")
                        .HasDatabaseName("idx_operator_trip_settlements_trip_code");

                    b.HasIndex("TripId")
                        .HasDatabaseName("idx_operator_trip_settlements_trip_id");

                    b.HasIndex("WalletTransactionId")
                        .HasDatabaseName("idx_operator_trip_settlements_wallet_transaction_id")
                        .HasFilter("wallet_transaction_id IS NOT NULL");

                    b.HasIndex("OperatorId", "Status")
                        .HasDatabaseName("idx_operator_trip_settlements_operator_status");

                    b.HasIndex("OperatorId", "TripId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_trip_settlements_operator_trip");

                    b.HasIndex("Status", "EligibleAt")
                        .HasDatabaseName("idx_operator_trip_settlements_status_eligible")
                        .HasFilter("status IN ('PENDING_HOLD','ELIGIBLE')");

                    b.HasIndex("Status", "ActiveFailureCode", "LastSettlementFailureAt")
                        .HasDatabaseName("idx_operator_trip_settlements_stuck")
                        .HasFilter("status = 'ELIGIBLE' AND active_failure_code IS NOT NULL");

                    b.ToTable("operator_trip_settlements", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_operator_trip_settlements_eligible_after_terminal", "eligible_at >= trip_terminal_at");

                            t.HasCheckConstraint("chk_operator_trip_settlements_failure_consistency", "(active_failure_code IS NULL) OR (status = 'ELIGIBLE' AND settlement_failure_count > 0 AND last_settlement_failure_at IS NOT NULL)");

                            t.HasCheckConstraint("chk_operator_trip_settlements_settled_consistency", "(status IN ('PENDING_HOLD','ELIGIBLE') AND settled_at IS NULL AND settlement_method IS NULL AND wallet_transaction_id IS NULL) OR (status IN ('SETTLED','CANCELLED') AND settled_at IS NOT NULL AND settlement_method IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.OperatorWallet", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OperatorId")
                        .HasName("pk_operator_wallets");

                    b.ToTable("operator_wallets", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_operator_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.OperatorWalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<OperatorWalletTransactionRef>("ReferenceType")
                        .HasColumnType("vietride_payment.operator_wallet_transaction_ref")
                        .HasColumnName("reference_type");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transaction_code");

                    b.Property<OperatorWalletTransactionType>("Type")
                        .HasColumnType("vietride_payment.operator_wallet_transaction_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_operator_wallet_transactions");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_wallet_transactions_code")
                        .HasFilter("transaction_code IS NOT NULL");

                    b.HasIndex("OperatorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_operator_wallet_transactions_operator_id_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_operator_wallet_transactions_reference")
                        .HasFilter("reference_id IS NOT NULL");

                    b.HasIndex("OperatorId", "Type", "ReferenceType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_wallet_transactions_subscription")
                        .HasFilter("reference_type = 'SUBSCRIPTION_PAYMENT'");

                    b.HasIndex("ReferenceType", "ReferenceId", "OperatorId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_operator_wallet_transactions_parcel_compensation")
                        .HasFilter("reference_type = 'PARCEL_COMPENSATION'");

                    b.ToTable("operator_wallet_transactions", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_operator_wallet_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_operator_wallet_transactions_balance_non_negative", "balance_before >= 0 AND balance_after >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.ParcelCompensationPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<Guid>("BeneficiaryUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_user_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FundingSource")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("funding_source");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_event_id");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcel_id");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_parcel_compensation_payouts");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ix_parcel_compensation_payouts_claim_id");

                    b.HasIndex("PaidEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_parcel_compensation_payouts_paid_event_id")
                        .HasFilter("paid_event_id IS NOT NULL");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_parcel_compensation_payouts_source_event_id")
                        .HasFilter("source_event_id IS NOT NULL");

                    b.HasIndex("OperatorId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_parcel_compensation_payouts_operator_id_status_created_at");

                    b.ToTable("parcel_compensation_payouts", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_parcel_compensation_payout_amount", "amount_vnd > 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<bool>("ContextReconciliationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("context_reconciliation_required");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("vietride_payment.payment_method")
                        .HasColumnName("method");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("PaymentRedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_redirect_url");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<PaymentReferenceType>("ReferenceType")
                        .HasColumnType("vietride_payment.payment_reference_type")
                        .HasColumnName("reference_type");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<VnPayReturnMode?>("ReturnMode")
                        .HasColumnType("vietride_payment.vnpay_return_mode")
                        .HasColumnName("vnpay_return_mode");

                    b.Property<PaymentStatus>("Status")
                        .HasColumnType("vietride_payment.payment_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vnpay_response_code");

                    b.Property<string>("VnPayTxnRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("SucceededAt")
                        .HasDatabaseName("idx_payments_subscription_succeeded_at")
                        .HasFilter("reference_type = 'SUBSCRIPTION' AND status = 'SUCCEEDED'");

                    b.HasIndex("VnPayTxnRef")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_vnpay_txn_ref")
                        .HasFilter("vnpay_txn_ref IS NOT NULL");

                    b.HasIndex("ContextReconciliationRequired", "Status")
                        .HasDatabaseName("idx_payments_context_reconciliation")
                        .HasFilter("context_reconciliation_required = TRUE");

                    b.HasIndex("OperatorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_payments_operator_id_created_at")
                        .HasFilter("operator_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_payments_reference");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_payments_status_created_at")
                        .HasFilter("status IN ('PENDING_REDIRECT'::vietride_payment.payment_status)");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_payments_user_id_created_at")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("payments", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_payments_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_platform_wallets");

                    b.ToTable("platform_wallets", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_platform_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<bool>("ActorSnapshotResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("actor_snapshot_resolved");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type")
                        .HasDefaultValueSql("'SYSTEM'");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<PlatformWalletTransactionRef>("ReferenceType")
                        .HasColumnType("vietride_payment.platform_wallet_transaction_ref")
                        .HasColumnName("reference_type");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transaction_code");

                    b.Property<PlatformWalletTransactionType>("Type")
                        .HasColumnType("vietride_payment.platform_wallet_transaction_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_platform_wallet_transactions");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("idx_platform_wallet_transactions_actor_user_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_platform_wallet_transactions_created_at");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_wallet_transactions_code")
                        .HasFilter("transaction_code IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_platform_wallet_transactions_reference")
                        .HasFilter("reference_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_wallet_transactions_parcel_compensation")
                        .HasFilter("reference_type = 'PARCEL_COMPENSATION'");

                    b.HasIndex("Type", "ReferenceType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_wallet_transactions_subscription")
                        .HasFilter("reference_type = 'SUBSCRIPTION_PAYMENT'");

                    b.ToTable("platform_wallet_transactions", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_platform_wallet_transactions_actor_type", "actor_type IN ('USER','SYSTEM')");

                            t.HasCheckConstraint("chk_platform_wallet_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_platform_wallet_transactions_balance_non_negative", "balance_before >= 0 AND balance_after >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWalletTransactionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AllocatedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("allocated_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<PlatformWalletTransactionLinkType>("LinkType")
                        .HasColumnType("vietride_payment.platform_wallet_transaction_link_type")
                        .HasColumnName("link_type");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("PlatformWalletTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_wallet_transaction_id");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_code");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_wallet_transaction_links");

                    b.HasIndex("OperatorId")
                        .HasDatabaseName("idx_platform_wallet_transaction_links_operator")
                        .HasFilter("operator_id IS NOT NULL");

                    b.HasIndex("PlatformWalletTransactionId")
                        .HasDatabaseName("idx_platform_wallet_transaction_links_transaction");

                    b.HasIndex("TripId")
                        .HasDatabaseName("idx_platform_wallet_transaction_links_trip")
                        .HasFilter("trip_id IS NOT NULL");

                    b.HasIndex("ReferenceId", "ReferenceCode")
                        .HasDatabaseName("idx_platform_wallet_transaction_links_reference")
                        .HasFilter("reference_id IS NOT NULL OR reference_code IS NOT NULL");

                    b.HasIndex("PlatformWalletTransactionId", "LinkType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_platform_wallet_transaction_links_identity");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PlatformWalletTransactionId", "LinkType", "ReferenceId"), false);

                    b.ToTable("platform_wallet_transaction_links", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_platform_wallet_tx_links_amount_non_negative", "allocated_amount >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.ProcessedIntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_processed_integration_events");

                    b.HasIndex("Consumer", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_processed_integration_events_consumer_event");

                    b.ToTable("processed_integration_events", "vietride_payment");
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.RefundFailureLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ParcelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcel_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("TriggerEventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_event_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refund_failure_logs");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("idx_refund_failure_logs_booking_id")
                        .HasFilter("booking_id IS NOT NULL");

                    b.HasIndex("LastAttemptAt")
                        .HasDatabaseName("idx_refund_failure_logs_unresolved")
                        .HasFilter("resolved_at IS NULL");

                    b.HasIndex("ParcelId")
                        .HasDatabaseName("idx_refund_failure_logs_parcel_id")
                        .HasFilter("parcel_id IS NOT NULL");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("idx_refund_failure_logs_resolved_by_user_id")
                        .HasFilter("resolved_by_user_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_refund_failure_logs_reference")
                        .HasFilter("reference_type IS NOT NULL AND reference_id IS NOT NULL");

                    b.ToTable("refund_failure_logs", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_refund_failure_logs_target_exists", "booking_id IS NOT NULL OR parcel_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.TopUpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("PaymentRedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_redirect_url");

                    b.Property<VnPayReturnMode?>("ReturnMode")
                        .HasColumnType("vietride_payment.vnpay_return_mode")
                        .HasColumnName("vnpay_return_mode");

                    b.Property<TopUpRequestStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_payment.top_up_request_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'::vietride_payment.top_up_request_status");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vnpay_response_code");

                    b.Property<string>("VnPayTxnRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("Id")
                        .HasName("pk_top_up_requests");

                    b.HasIndex("VnPayTxnRef")
                        .IsUnique()
                        .HasDatabaseName("uq_top_up_requests_vnpay_txn_ref");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_top_up_requests_status_created_at")
                        .HasFilter("status = 'PENDING'::vietride_payment.top_up_request_status");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_top_up_requests_user_id_created_at");

                    b.ToTable("top_up_requests", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_top_up_requests_amount_min", "amount >= 10000");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_wallets");

                    b.ToTable("wallets", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<WalletTransactionRef>("ReferenceType")
                        .HasColumnType("vietride_payment.wallet_transaction_ref")
                        .HasColumnName("reference_type");

                    b.Property<WalletTransactionType>("Type")
                        .HasColumnType("vietride_payment.wallet_transaction_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_wallet_transactions_reference")
                        .HasFilter("reference_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_wallet_transactions_user_id_created_at");

                    b.ToTable("wallet_transactions", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_wallet_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_wallet_transactions_balance_non_negative", "balance_before >= 0 AND balance_after >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxDlq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("TerminalAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_outbox_dlq");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_outbox_dlq_event_id");

                    b.HasIndex("TerminalAt", "EventId")
                        .IsDescending()
                        .HasDatabaseName("idx_outbox_dlq_terminal_event_id");

                    b.ToTable("outbox_dlq", "vietride_payment");
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("vietride_payment.outbox_event_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING'::vietride_payment.outbox_event_status, 'PUBLISHING'::vietride_payment.outbox_event_status, 'FAILED'::vietride_payment.outbox_event_status)");

                    b.ToTable("outbox_events", "vietride_payment");
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("VietRide.Payment.Domain.Entities.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_payments_payment_id");
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.OperatorTripSettlement", b =>
                {
                    b.HasOne("VietRide.Payment.Domain.Entities.OperatorWalletTransaction", null)
                        .WithMany()
                        .HasForeignKey("WalletTransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operator_trip_settlements_operator_wallet_transactions_wall~");
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWalletTransactionLink", b =>
                {
                    b.HasOne("VietRide.Payment.Domain.Entities.PlatformWalletTransaction", null)
                        .WithMany()
                        .HasForeignKey("PlatformWalletTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platform_wallet_transaction_links_transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
