// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VietRide.Payment.Domain.Enums;
using VietRide.Payment.Infrastructure;

#nullable disable

namespace VietRide.Payment.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vietride_payment")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "outbox_event_status", new[] { "PENDING", "PUBLISHING", "PUBLISHED", "FAILED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "WALLET", "VNPAY" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_reference_type", new[] { "BOOKING", "BOOKING_GROUP", "PARCEL", "TOP_UP", "SUBSCRIPTION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status", new[] { "PENDING_REDIRECT", "SUCCEEDED", "FAILED", "EXPIRED", "REFUNDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "platform_wallet_transaction_ref", new[] { "BOOKING_PAYMENT_HOLD", "PARCEL_PAYMENT_HOLD", "BOOKING_REFUND", "PARCEL_REFUND", "TRIP_SETTLEMENT", "SUBSCRIPTION_PAYMENT", "MANUAL_ADJUSTMENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "platform_wallet_transaction_type", new[] { "CREDIT", "DEBIT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "top_up_request_status", new[] { "PENDING", "SUCCEEDED", "FAILED", "EXPIRED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wallet_transaction_ref", new[] { "TOP_UP", "BOOKING_PAYMENT", "BOOKING_REFUND", "PARCEL_PAYMENT", "PARCEL_REFUND", "MANUAL_ADJUSTMENT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wallet_transaction_type", new[] { "CREDIT", "DEBIT" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<PaymentMethod>("Method")
                        .IsRequired()
                        .HasColumnType("payment_method")
                        .HasColumnName("method");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("PaymentRedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_redirect_url");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<PaymentReferenceType>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("payment_reference_type")
                        .HasColumnName("reference_type");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<PaymentStatus>("Status")
                        .IsRequired()
                        .HasColumnType("payment_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vnpay_response_code");

                    b.Property<string>("VnPayTxnRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("VnPayTxnRef")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_vnpay_txn_ref")
                        .HasFilter("vnpay_txn_ref IS NOT NULL");

                    b.HasIndex("OperatorId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_payments_operator_id_created_at")
                        .HasFilter("operator_id IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_payments_reference");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_payments_status_created_at")
                        .HasFilter("status IN ('PENDING_REDIRECT')");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_payments_user_id_created_at")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("payments", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_payments_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_platform_wallets");

                    b.ToTable("platform_wallets", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_platform_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.PlatformWalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<PlatformWalletTransactionRef>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("platform_wallet_transaction_ref")
                        .HasColumnName("reference_type");

                    b.Property<PlatformWalletTransactionType>("Type")
                        .IsRequired()
                        .HasColumnType("platform_wallet_transaction_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_platform_wallet_transactions");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_platform_wallet_transactions_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_platform_wallet_transactions_reference")
                        .HasFilter("reference_id IS NOT NULL");

                    b.ToTable("platform_wallet_transactions", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_platform_wallet_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_platform_wallet_transactions_balance_non_negative", "balance_before >= 0 AND balance_after >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.TopUpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("PaymentRedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("payment_redirect_url");

                    b.Property<TopUpRequestStatus>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("top_up_request_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vnpay_response_code");

                    b.Property<string>("VnPayTxnRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("Id")
                        .HasName("pk_top_up_requests");

                    b.HasIndex("VnPayTxnRef")
                        .IsUnique()
                        .HasDatabaseName("uq_top_up_requests_vnpay_txn_ref");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_top_up_requests_status_created_at")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_top_up_requests_user_id_created_at");

                    b.ToTable("top_up_requests", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_top_up_requests_amount_min", "amount >= 10000");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_wallets");

                    b.ToTable("wallets", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Payment.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<WalletTransactionRef>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("wallet_transaction_ref")
                        .HasColumnName("reference_type");

                    b.Property<WalletTransactionType>("Type")
                        .IsRequired()
                        .HasColumnType("wallet_transaction_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("idx_wallet_transactions_reference")
                        .HasFilter("reference_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_wallet_transactions_user_id_created_at");

                    b.ToTable("wallet_transactions", "vietride_payment", t =>
                        {
                            t.HasCheckConstraint("chk_wallet_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("chk_wallet_transactions_balance_non_negative", "balance_before >= 0 AND balance_after >= 0");
                        });
                });

            modelBuilder.Entity("VietRide.Shared.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("outbox_event_status")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_outbox_events_status_created")
                        .HasFilter("status IN ('PENDING', 'PUBLISHING', 'FAILED')");

                    b.ToTable("outbox_events", "vietride_payment");
                });
#pragma warning restore 612, 618
        }
    }
}
