namespace VietRide.Identity.Domain.Enums;

public enum ActivityLogAction
{
    LOGIN,
    LOGOUT,
    BOOK_TICKET,
    CANCEL_TICKET,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    COMPLETE_PROFILE,
    CREATE_OPERATOR,
    APPROVE_OPERATOR,
    REJECT_OPERATOR,
    LOCK_USER,
    UNLOCK_USER,
    VEHICLE_SUBSTITUTION_TRIGGERED,
    DRIVER_SCHEDULE_EDIT,
    VEHICLE_SWAP,
    TRIP_COMPLETED_MANUAL,
    PARCEL_UNLOAD_OVERRIDE,
    PARCEL_DELIVERY_RESEND,
    PARCEL_MANUAL_CONFIRM,
    TRIP_SETTLEMENT_MANUAL,
    OPERATOR_WALLET_ADJUSTMENT,
    SET_INITIAL_PASSWORD,
    RESEND_INITIAL_PASSWORD,
    STATION_MERGED,
    STATION_NORMALIZED
}
